### ISSUE TITLE
Error on `ddev start`

### ISSUE THREAD

**Issue by stasadev** [MurzNN/ddev-pgadmin#1]
From Discord https://discord.com/channels/664580571770388500/1068592266752573440/1295406169229234208

```
$ ddev logs -s pgadmin
You need to define the PGADMIN_DEFAULT_EMAIL and PGADMIN_DEFAULT_PASSWORD or PGADMIN_DEFAULT_PASSWORD_FILE environment variables.
```

---

1. I was able to start pgAdmin using these variables in `.ddev/docker-compose.pgadmin.yaml`:

	```yaml
	services:
	  pgadmin:
	    environment:
          - VIRTUAL_HOST=pgadmin.$DDEV_HOSTNAME
          - HTTP_EXPOSE=80:80
          - HTTPS_EXPOSE=443:80
	      - PGADMIN_CONFIG_SERVER_MODE=False
	      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
	      - PGADMIN_CONFIG_DESKTOP_USER="pgadmin@$DDEV_HOSTNAME"
	      - PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS=["$DDEV_TLD"]
	      - PGADMIN_DEFAULT_EMAIL=pgadmin@$DDEV_HOSTNAME
	      - PGADMIN_DEFAULT_PASSWORD=db
	```

2. There is an extra `:` in the command, that must be removed:

	https://github.com/MurzNN/ddev-pgadmin/blob/5bdb2a440ed9ed3298472f4427234bd48c735ff8/commands/host/pgadmin#L3

3. Please add `#ddev-generated` to add-on files `docker-compose.pgadmin.yaml` and `commands/host/pgadmin` , so it's properly removed on `ddev get --remove pgadmin` and use `removal_actions` in `install.yaml` to cleanup `.ddev/pgadmin` folder https://ddev.readthedocs.io/en/stable/users/extend/additional-services/#sections-and-features-of-ddev-get-add-on-installyaml

Thank you.
